version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 ecommerce.asgi:application"
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - '8000:8000'
    environment:
      - DEBUG=1
      - SECRET_KEY=changeme
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://ecommerce_user:ecommerce_pass@db:5432/ecommerce
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: 